/* Āyus Catalog — educational product graph (nutraceuticals, vitamins, classical forms).
   NOT medical advice / not a pharmacy. Cross-links goals, doshas, conditions. */
window.AYUS_CATALOG = {
  meta: {
    version: 1,
    disclaimer:
      "Educational information only. Not a marketplace checkout, diagnosis, prescription, or substitute for professional care. Always verify labels, consult a qualified clinician, and check interactions—especially if pregnant, nursing, on medication, or managing a condition.",
    categories: [
      { id: "classical", label: "Classical formulas", icon: "flask" },
      { id: "herb_single", label: "Single herbs", icon: "leaf" },
      { id: "vitamin", label: "Vitamins & minerals", icon: "sun" },
      { id: "nutraceutical", label: "Nutraceuticals", icon: "capsule" },
      { id: "daily", label: "Daily essentials", icon: "spark" }
    ]
  },
  products: [
    {
      id: "triphala_tab",
      name: "Triphala",
      form: "tablet / churna",
      category: "classical",
      brand_type: "classical",
      sanskrit: "Triphalā",
      links: { formulation: "triphala", herbs: ["amalaki", "haritaki", "bibhitaki"] },
      goals: ["digestion", "immunity", "weight"],
      doshas: ["vata", "pitta", "kapha"],
      conditions: ["constipation", "agnimandya"],
      summary: "Three-fruit classic for gentle overnight cleansing and gut rhythm.",
      evidence_note: "Traditional use is extensive; modern trials exist for bowel regularity—quality varies by brand.",
      typical_use: "As directed on label; classically often at night with warm water.",
      safety: ["Start low", "Avoid if loose stools", "Discuss with clinician if pregnant or on meds"],
      tags: ["gut", "rasayana", "evening"]
    },
    {
      id: "ashwagandha_cap",
      name: "Ashwagandha",
      form: "capsule / extract",
      category: "herb_single",
      brand_type: "nutraceutical",
      sanskrit: "Aśvagandhā",
      links: { herbs: ["ashwagandha"] },
      goals: ["stress", "sleep", "energy", "focus"],
      doshas: ["vata", "kapha"],
      conditions: ["stress", "sleep", "fatigue"],
      summary: "Adaptogen traditionally used for stress resilience, sleep quality, and vitality.",
      evidence_note: "Several human studies on stress/sleep; extract standardization and dose matter.",
      typical_use: "Evening or split doses per product label; often with warm milk/water.",
      safety: ["May interact with thyroid, sedatives, immunosuppressants", "Not for pregnancy unless advised", "Watch for GI upset"],
      tags: ["stress", "sleep", "adaptogen"]
    },
    {
      id: "turmeric_curcumin",
      name: "Turmeric / Curcumin",
      form: "capsule / tablet",
      category: "nutraceutical",
      brand_type: "nutraceutical",
      sanskrit: "Haridrā",
      links: { herbs: ["turmeric"] },
      goals: ["immunity", "skin", "energy"],
      doshas: ["kapha", "vata"],
      conditions: ["joint_discomfort", "skin_health", "inflammation"],
      summary: "Kitchen spice elevated to standardized extracts for joints and metabolic support.",
      evidence_note: "Clinical interest in curcumin for joints/inflammation; bioavailability formulas differ.",
      typical_use: "With meals; often with black pepper (piperine) for absorption—check label.",
      safety: ["May affect blood thinning / gallbladder issues", "GI sensitivity possible", "Check drug interactions"],
      tags: ["joints", "inflammation", "daily"]
    },
    {
      id: "brahmi_cap",
      name: "Brahmi (Bacopa)",
      form: "capsule / syrup",
      category: "herb_single",
      brand_type: "nutraceutical",
      sanskrit: "Brāhmī",
      links: { herbs: ["brahmi"] },
      goals: ["focus", "stress", "sleep"],
      doshas: ["vata", "pitta"],
      conditions: ["memory_focus", "stress"],
      summary: "Medhya rasāyana—traditionally for calm focus and mental clarity.",
      evidence_note: "Bacopa studies on cognition exist; effects are gradual over weeks.",
      typical_use: "Daily consistency matters more than one-off high doses.",
      safety: ["May cause nausea on empty stomach", "Sedation in some people", "Not a substitute for clinical mental-health care"],
      tags: ["focus", "mind", "medhya"]
    },
    {
      id: "vitamin_d3",
      name: "Vitamin D3",
      form: "softgel / tablet / drops",
      category: "vitamin",
      brand_type: "nutraceutical",
      summary: "Foundational nutrient for bone, immunity, and mood pathways—especially with low sun exposure.",
      goals: ["immunity", "energy", "mood"],
      doshas: ["vata", "kapha"],
      conditions: ["fatigue", "low_immunity"],
      evidence_note: "Deficiency is common; dosing should follow labs/clinician guidance.",
      typical_use: "With a meal containing fat; dose individualized.",
      safety: ["Excess can be toxic—avoid mega-dosing without labs", "Fat-soluble: stores in body"],
      tags: ["foundation", "labs", "daily"],
      lab_hint: "25-OH vitamin D blood test when possible"
    },
    {
      id: "vitamin_b_complex",
      name: "B-Complex",
      form: "tablet / capsule",
      category: "vitamin",
      brand_type: "nutraceutical",
      summary: "Energy metabolism support—especially useful with high stress, restricted diets, or fatigue patterns.",
      goals: ["energy", "focus", "stress"],
      doshas: ["vata", "pitta"],
      conditions: ["fatigue", "stress"],
      evidence_note: "Corrects deficiency states; not a stimulant for everyone.",
      typical_use: "Morning with food (B vitamins can feel activating).",
      safety: ["Bright yellow urine is common (riboflavin)", "High B6 chronic excess may cause neuropathy"],
      tags: ["energy", "morning", "stress"]
    },
    {
      id: "magnesium_glycinate",
      name: "Magnesium (glycinate)",
      form: "capsule / powder",
      category: "vitamin",
      brand_type: "nutraceutical",
      summary: "Calming mineral often chosen for sleep, muscle ease, and evening wind-down.",
      goals: ["sleep", "stress", "energy"],
      doshas: ["vata", "pitta"],
      conditions: ["sleep", "stress", "headache"],
      evidence_note: "Helpful when intake is low; form matters (glycinate gentler than oxide for many).",
      typical_use: "Evening; start low to assess bowel tolerance.",
      safety: ["Loose stools if dose high", "Kidney disease: clinician only", "May interact with some antibiotics"],
      tags: ["sleep", "evening", "nervous-system"]
    },
    {
      id: "omega3",
      name: "Omega-3 (EPA/DHA)",
      form: "softgel / liquid",
      category: "nutraceutical",
      brand_type: "nutraceutical",
      summary: "Essential fats supporting heart, brain, and inflammatory balance.",
      goals: ["focus", "immunity", "skin"],
      doshas: ["vata", "pitta"],
      conditions: ["heart_wellness", "memory_focus", "skin_health"],
      evidence_note: "Strong research base for lipids/heart; purity/oxidation of oil matters.",
      typical_use: "With meals; refrigerate liquid forms when advised.",
      safety: ["May thin blood at high doses", "Fish allergy caution", "Quality: third-party tested preferred"],
      tags: ["heart", "brain", "daily"]
    },
    {
      id: "probiotic_multi",
      name: "Multi-strain probiotic",
      form: "capsule",
      category: "nutraceutical",
      brand_type: "nutraceutical",
      summary: "Supports gut ecosystem—pairs well with digestion goals and after dietary upheaval.",
      goals: ["digestion", "immunity", "skin"],
      doshas: ["vata", "kapha"],
      conditions: ["agnimandya", "ibs", "diarrhea"],
      evidence_note: "Strain-specific; not all products are equal. Food-first (ferments) still counts.",
      typical_use: "As labeled; some prefer empty stomach, others with food.",
      safety: ["Immunocompromised: clinician first", "Initial bloating possible", "Store per label"],
      tags: ["gut", "microbiome"]
    },
    {
      id: "chyawanprash",
      name: "Chyawanprash",
      form: "lehyam / jam",
      category: "classical",
      brand_type: "classical",
      sanskrit: "Cyavanaprāśa",
      links: { formulation: "chyawanprash" },
      goals: ["immunity", "energy", "respiratory"],
      doshas: ["vata", "kapha"],
      conditions: ["low_immunity", "cold_cough", "fatigue"],
      summary: "Classic rejuvenative jam for seasonal resilience and vitality.",
      evidence_note: "Traditional rasāyana; modern studies mixed—quality and sugar content vary.",
      typical_use: "1 tsp morning, often with warm milk/water—adjust for sugar load.",
      safety: ["Sugar content—caution in blood sugar concerns", "Allergy to ingredients", "Not for everyone with high Kapha/weight goals without guidance"],
      tags: ["immunity", "winter", "rasayana"]
    },
    {
      id: "sitopaladi",
      name: "Sitopaladi churna",
      form: "powder / tablet",
      category: "classical",
      brand_type: "classical",
      sanskrit: "Sītopalādi",
      links: { formulation: "sitopaladi" },
      goals: ["immunity", "respiratory"],
      doshas: ["kapha", "vata"],
      conditions: ["cold_cough", "respiratory_support"],
      summary: "Traditional respiratory-support formula with honey or ghee vehicles.",
      evidence_note: "Classical indication for cough/cold patterns; modern RCTs limited.",
      typical_use: "Small dose with honey as traditionally guided; follow product label.",
      safety: ["Sugar base", "Not for uncontrolled diabetes without advice", "Seek care for severe respiratory symptoms"],
      tags: ["respiratory", "seasonal"]
    },
    {
      id: "guggulu_tab",
      name: "Guggulu (commiphora)",
      form: "tablet",
      category: "classical",
      brand_type: "classical",
      sanskrit: "Guggulu",
      links: { herbs: ["guggul"] },
      goals: ["weight", "skin", "joints"],
      doshas: ["kapha", "vata"],
      conditions: ["weight_management", "joint_discomfort", "skin_health"],
      summary: "Resin traditionally used in metabolic and joint formulas (e.g. Triphala Guggulu).",
      evidence_note: "Some lipid research; interactions and quality are real concerns.",
      typical_use: "Only under guidance if on thyroid/cholesterol meds.",
      safety: ["May interact with thyroid meds & statins", "GI upset", "Clinician recommended"],
      tags: ["metabolic", "joints", "advanced"]
    },
    {
      id: "zinc_picolinate",
      name: "Zinc",
      form: "tablet / capsule",
      category: "vitamin",
      brand_type: "nutraceutical",
      summary: "Trace mineral for immunity, skin, and tissue repair—easy to under- or overdo.",
      goals: ["immunity", "skin", "energy"],
      doshas: ["kapha", "pitta"],
      conditions: ["low_immunity", "skin_health", "cold_cough"],
      evidence_note: "Useful in deficiency; chronic high doses can lower copper.",
      typical_use: "With food if nauseating; short courses for colds sometimes used.",
      safety: ["Do not exceed long-term high doses", "Copper balance", "Nausea on empty stomach"],
      tags: ["immunity", "skin"]
    },
    {
      id: "iron_gentle",
      name: "Iron (gentle form)",
      form: "tablet / bisglycinate",
      category: "vitamin",
      brand_type: "nutraceutical",
      summary: "For clinically confirmed iron needs (fatigue, heavy cycles)—lab-guided only.",
      goals: ["energy"],
      doshas: ["pitta", "vata"],
      conditions: ["fatigue", "menstrual_wellness"],
      evidence_note: "Treat deficiency with labs; not a casual energy pill.",
      typical_use: "As directed after blood work; vitamin C can aid absorption.",
      safety: ["Keep away from children (toxicity)", "Constipation/black stool", "Do not self-dose without labs"],
      tags: ["labs-required", "energy", "women"]
    },
    {
      id: "amla_vitamin_c",
      name: "Amla (natural vitamin C)",
      form: "powder / capsule / candy",
      category: "herb_single",
      brand_type: "nutraceutical",
      sanskrit: "Āmalakī",
      links: { herbs: ["amla"] },
      goals: ["immunity", "skin", "digestion"],
      doshas: ["pitta", "vata", "kapha"],
      conditions: ["low_immunity", "skin_health", "hair_health"],
      summary: "Sour rasāyana fruit—traditionally cooling, rejuvenating, and C-rich.",
      evidence_note: "Food-form vitamin C with polyphenols; gentler than some megadose tablets.",
      typical_use: "Morning powder in water or as capsule with food.",
      safety: ["Acidity if sensitive", "Prefer food forms for daily use"],
      tags: ["immunity", "rasayana", "skin"]
    },
    {
      id: "shatavari_cap",
      name: "Shatavari",
      form: "capsule / powder",
      category: "herb_single",
      brand_type: "nutraceutical",
      sanskrit: "Śatāvarī",
      links: { herbs: ["shatavari"] },
      goals: ["energy", "stress"],
      doshas: ["vata", "pitta"],
      conditions: ["menstrual_wellness", "vitality"],
      summary: "Traditional women's tonic and cooling rejuvenative for vitality and balance.",
      evidence_note: "Mostly traditional + preliminary research; individual response varies.",
      typical_use: "With warm milk or water as labeled.",
      safety: ["Avoid if estrogen-sensitive conditions without clinician advice", "Allergy caution"],
      tags: ["women", "rasayana", "cooling"]
    },
    {
      id: "tulsi_tea",
      name: "Tulsi (holy basil)",
      form: "tea / capsule",
      category: "daily",
      brand_type: "food",
      sanskrit: "Tulasī",
      links: { herbs: ["tulsi"] },
      goals: ["stress", "immunity", "respiratory"],
      doshas: ["kapha", "vata"],
      conditions: ["stress", "cold_cough", "low_immunity"],
      summary: "Daily adaptogenic tea herb for calm clarity and seasonal airways.",
      evidence_note: "Promising stress research; tea is a gentle entry point.",
      typical_use: "1–2 cups daily as tea.",
      safety: ["May lower blood sugar—monitor if diabetic", "Pregnancy: check with clinician"],
      tags: ["tea", "daily", "stress"]
    },
    {
      id: "ginger_digest",
      name: "Ginger",
      form: "tea / capsule / fresh",
      category: "daily",
      brand_type: "food",
      sanskrit: "Ārdraka / Śuṇṭhī",
      links: { herbs: ["ginger"] },
      goals: ["digestion", "immunity", "nausea"],
      doshas: ["kapha", "vata"],
      conditions: ["agnimandya", "nausea", "cold_cough"],
      summary: "Universal digestive kindler—fresh tea before meals is classic dinacharya.",
      evidence_note: "Strong evidence for nausea; traditional for agni.",
      typical_use: "Fresh tea before meals or crystallized ginger in small amounts.",
      safety: ["Heartburn if excess", "Blood-thinning caution at high supplemental doses"],
      tags: ["digestion", "daily", "kitchen"]
    },
    {
      id: "collagen_peptide",
      name: "Collagen peptides",
      form: "powder",
      category: "nutraceutical",
      brand_type: "nutraceutical",
      summary: "Protein support popular for skin, joints, and recovery—works best with vitamin C and protein-rich diet.",
      goals: ["skin", "joints", "energy"],
      doshas: ["vata"],
      conditions: ["skin_health", "joint_discomfort", "hair_health"],
      evidence_note: "Growing evidence for skin elasticity/joints; not a complete protein for all needs.",
      typical_use: "Mixed in warm drinks; morning or post-activity.",
      safety: ["Source: bovine/marine—allergy/diet preferences", "Not vegan"],
      tags: ["skin", "joints", "protein"]
    },
    {
      id: "multivitamin_daily",
      name: "Daily multivitamin",
      form: "tablet",
      category: "vitamin",
      brand_type: "nutraceutical",
      summary: "Coverage for dietary gaps—not a replacement for meals or targeted lab-based therapy.",
      goals: ["immunity", "energy"],
      doshas: ["vata", "pitta", "kapha"],
      conditions: ["fatigue", "low_immunity"],
      evidence_note: "Helpful as insurance; excess megavitamins are not better.",
      typical_use: "With breakfast.",
      safety: ["Check iron content if not needed", "Avoid stacking with other high-dose singles blindly"],
      tags: ["foundation", "daily"]
    }
  ],
  /* How catalog products relate to lifestyle slots */
  stack_slots: [
    { id: "morning", label: "Morning", sk: "Prātaḥ" },
    { id: "with_meals", label: "With meals", sk: "Bhojana" },
    { id: "evening", label: "Evening", sk: "Sāyaṃ" },
    { id: "night", label: "Night", sk: "Rātri" },
    { id: "as_needed", label: "As needed", sk: "Yathāyogya" }
  ]
};
