/* Curated feed / stories / reels content — wellness Instagram-style (educational) */
window.AYUS_ENGAGE = {
  version: 5,
  stories: [
    { id: 's_ritual', title: 'Ritual', gradient: 'g1', icon: '🪔', kind: 'tip', body: 'Warm water on rising wakes agni gently. Sip slowly, no rush.', cta: 'Mark done', action: 'habit:warm_water' },
    { id: 's_dosha', title: 'Dosha', gradient: 'g2', icon: '⚖', kind: 'quiz', body: 'Your prakṛti is the map. A 1-minute quiz personalises everything.', cta: 'Take quiz', action: 'openQuiz' },
    { id: 's_herb', title: 'Herb', gradient: 'g3', icon: '🌿', kind: 'herb', body: 'Ashwagandha — traditional ally for stress resilience and deeper rest.', cta: 'Open herb', action: 'openHerb:ashwagandha' },
    { id: 's_breath', title: 'Breath', gradient: 'g4', icon: '🌬️', kind: 'tip', body: '4 counts in · 6 counts out. Two minutes can settle a racing mind.', cta: 'I did this', action: 'habit:breathe' },
    { id: 's_catalog', title: 'Stack', gradient: 'g5', icon: '✦', kind: 'catalog', body: 'Build a gentle stack: magnesium at night, tulsi tea by day.', cta: 'Browse', action: 'go:market' },
    { id: 's_sleep', title: 'Sleep', gradient: 'g6', icon: '🌙', kind: 'tip', body: 'Screens out 45 min before bed. Kapha hours gift the deepest rest.', cta: 'Save tip', action: 'savePost:p_sleep' },
    { id: 's_check', title: 'Check-in', gradient: 'g1', icon: '◎', kind: 'checkin', body: 'Something off today? A 60-second check-in yields cited guidance.', cta: 'Check-in', action: 'startCheckin' },
    { id: 's_heritage', title: 'Roots', gradient: 'g3', icon: '📜', kind: 'heritage', body: 'Āyurveda = āyus (life) + veda (knowledge). 5,000 years, still living.', cta: 'Explore', action: 'go:heritage' }
  ],
  posts: [
    {
      id: 'p_morning',
      type: 'ritual',
      author: 'Āyus Rituals',
      handle: '@dinacharya',
      avatar: '🌅',
      title: 'The 5-minute morning that changes your day',
      body: 'Tongue scrape · warm water · three slow breaths · set one intention. Ojas loves consistency more than intensity.',
      tags: ['morning', 'agni', 'habit'],
      media: 'gradient-sunrise',
      likes: 1284,
      saves: 402
    },
    {
      id: 'p_ashwa',
      type: 'herb',
      author: 'Apothecary',
      handle: '@materia',
      avatar: '🌿',
      title: 'Ashwagandha — not hype, a chain of evidence',
      body: 'Classical rasāyana + modern stress trials. Always check interactions (thyroid, sedatives) and quality of extract.',
      tags: ['adaptogen', 'stress', 'sleep'],
      media: 'gradient-forest',
      herbId: 'ashwagandha',
      likes: 2103,
      saves: 891
    },
    {
      id: 'p_sleep',
      type: 'guide',
      author: 'Sleep Lab',
      handle: '@nidra',
      avatar: '🌙',
      title: 'Why 10pm is a Kapha gift',
      body: 'Fall asleep as Kapha rises (evening heaviness). Fighting until Pitta-night hours often means wired + tired.',
      tags: ['sleep', 'circadian'],
      media: 'gradient-night',
      likes: 956,
      saves: 512
    },
    {
      id: 'p_gut',
      type: 'guide',
      author: 'Agni Notes',
      handle: '@agni',
      avatar: '🔥',
      title: 'Lunch is the main event',
      body: 'Digestive fire peaks midday. Make lunch substantial; keep dinner light. Your evening self will thank you.',
      tags: ['digestion', 'meals'],
      media: 'gradient-ember',
      likes: 1740,
      saves: 633
    },
    {
      id: 'p_challenge',
      type: 'challenge',
      author: 'Āyus Challenges',
      handle: '@streak',
      avatar: '✨',
      title: '7-day warm water streak',
      body: 'One glass on rising, every day this week. Tap complete on Today rituals. Streaks build identity, not guilt.',
      tags: ['challenge', '7day'],
      media: 'gradient-gold',
      challengeId: 'warm_water_7',
      likes: 3201,
      saves: 1102
    },
    {
      id: 'p_triphala',
      type: 'formula',
      author: 'Classics',
      handle: '@brhattrayi',
      avatar: '📜',
      title: 'Triphala: the three-fruit nightcap',
      body: 'Gentle overnight support for elimination. Start low. Not for loose stools. Educational — not a prescription.',
      tags: ['gut', 'classical'],
      media: 'gradient-sage',
      productId: 'triphala_tab',
      likes: 1444,
      saves: 720
    },
    {
      id: 'p_breath',
      type: 'reel',
      author: 'Prāṇa',
      handle: '@breath',
      avatar: '🌬️',
      title: 'Box breath in 30 seconds',
      body: 'In 4 · hold 4 · out 4 · hold 4. Repeat 4 rounds. Save this for anxious afternoons.',
      tags: ['reel', 'breath', 'stress'],
      media: 'gradient-sky',
      likes: 4521,
      saves: 2004,
      duration: '0:30'
    },
    {
      id: 'p_oil',
      type: 'ritual',
      author: 'Āyus Rituals',
      handle: '@dinacharya',
      avatar: '🫒',
      title: 'Abhyaṅga — oil as nervous-system medicine',
      body: 'Warm sesame or coconut oil, 5 minutes before bath. Vāta softens. Sleep deepens. Start with feet if short on time.',
      tags: ['oil', 'vata', 'evening'],
      media: 'gradient-amber',
      likes: 1888,
      saves: 940
    },
    {
      id: 'p_vitamin_d',
      type: 'catalog',
      author: 'Nutri Desk',
      handle: '@nutra',
      avatar: '☀️',
      title: 'Vitamin D: sun, food, then labs',
      body: 'Many feel better when deficiency is corrected — but dose is lab-guided. Don’t mega-dose solo.',
      tags: ['vitamin', 'labs'],
      media: 'gradient-sun',
      productId: 'vitamin_d3',
      likes: 990,
      saves: 401
    },
    {
      id: 'p_pitta',
      type: 'dosha',
      author: 'Dosha Daily',
      handle: '@tridosha',
      avatar: '🔥',
      title: 'Pitta days: cool the fire',
      body: 'Skip midday heat arguments. Coconut, mint, moon walks, less coffee. Channel intensity into craft, not conflict.',
      tags: ['pitta', 'summer'],
      media: 'gradient-coral',
      likes: 1302,
      saves: 550
    },
    {
      id: 'p_reel_yoga',
      type: 'reel',
      author: 'Move Softly',
      handle: '@asana',
      avatar: '🧘',
      title: 'Cat-cow for stuck digestion',
      body: '8 slow rounds after lunch. Pair with a short walk. Motion is medicine for Kapha stagnation.',
      tags: ['reel', 'yoga', 'gut'],
      media: 'gradient-mint',
      likes: 2890,
      saves: 1200,
      duration: '0:45'
    },
    {
      id: 'p_honesty',
      type: 'trust',
      author: 'Āyus Trust',
      handle: '@evidence',
      avatar: '🔗',
      title: 'Why we show evidence tiers',
      body: 'Classical ≠ clinical. We never blur them. Your trust is the product.',
      tags: ['trust', 'evidence'],
      media: 'gradient-ink',
      likes: 760,
      saves: 390
    }
  ],
  challenges: [
    { id: 'warm_water_7', title: 'Warm water × 7', days: 7, habit: 'warm_water', reward: 'Agni Starter', xp: 70 },
    { id: 'breath_5', title: 'Breath practice × 5', days: 5, habit: 'breathe', reward: 'Calm Spark', xp: 50 },
    { id: 'journal_7', title: 'Journal × 7', days: 7, habit: 'journal', reward: 'Self Witness', xp: 80 },
    { id: 'sleep_wind_5', title: 'Wind-down × 5', days: 5, habit: 'early_wind', reward: 'Night Lotus', xp: 55 }
  ],
  achievements: [
    { id: 'first_checkin', title: 'First listen', desc: 'Complete a wellness check-in', icon: '◎' },
    { id: 'prakriti', title: 'Know thyself', desc: 'Finish the dosha quiz', icon: '⚖' },
    { id: 'streak_3', title: 'Three-day flame', desc: 'Keep a 3-day streak', icon: '🪔' },
    { id: 'streak_7', title: 'Week of ojas', desc: '7-day streak', icon: '✨' },
    { id: 'stack_3', title: 'Stack builder', desc: 'Add 3 items to My Stack', icon: '☰' },
    { id: 'saved_5', title: 'Curator', desc: 'Save 5 feed posts', icon: '🔖' },
    { id: 'journal_3', title: 'Inner scribe', desc: '3 journal entries', icon: '✎' }
  ]
};
